### ISSUE TITLE
browser-update script does not work in https mode

### ISSUE THREAD

**Issue by bytecodeman** [browser-update/browser-update#266]
I'm running your code on a page that forces https by redirecting the page to use https.

Your code just does not pop up a warning when run using IE8.  It loads the script but no warning bar shows.  It does work if I do not force https.

I tried everything I can think of to make it work.  The code to invoke the warning bar now looks like this:

$(function(){
  var e = document.createElement("script"); 
  e.src = "//browser-update.org/update.min.js"; 
  e.type = "text/javascript";
  document.getElementsByTagName("head")[0].appendChild(e);
});

Please help! :-(

**Comment by clst** [comment]
This must be a problem with either TLS or the ECDHE encryption of the SSL Server. There is no suitable cipher suite available that is still supported under XP.  
You would also not be able to open https://browser-update.org on that system.  
Compare here: https://www.ssllabs.com/ssltest/analyze.html?d=browser-update.org&latest under handshake simulation.  
The server configuration is exemplary, it is just not that useful to have it serve the browser-update bar ;) Too secure...

**Comment by bytecodeman** [comment]
You are correct.  The ssltest shows a problem wil the encryption on XP.

Wasn't aware of that.

Thanks for getting back to me!

On Thu, Sep 3, 2015 at 10:41 AM, clst <notifications@github.com> wrote:

> This must be a problem with either TLS or the ECDHE encryption of the SSL
> Server. There is no suitable cipher suite available that is still supported
> under XP.
>
> You would also not be able to open https://browser-update.org on that
> system.
>
> Compare here:
> https://www.ssllabs.com/ssltest/analyze.html?d=browser-update.org&latest
> under handshake simulation.
>
> The server configuration is exemplary, it is just not that useful to have
> it serve the browser-update bar ;) Too secure...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/browser-update/browser-update/issues/266#issuecomment-137470297>
> .
>



-- 
Antonio C. Silvestri
Professor of Computer Science / Webmaster
Springfield Technical Community College
1 Armory Square
Springfield, MA 01102-9000

Office: Building 17  Room 415  Testing Center

-- 
*SPRINGFIELD TECHNICAL COMMUNITY COLLEGE*
*IMPORTANT:  The information contained in this e-mail is intended solely 
for the person or entity to which it is addressed and may contain 
confidential and/or legally privileged material. Any use, disclosure, or 
taking of any action in reliance upon this information by any person and/or 
entity other than the intended recipient is prohibited and may be unlawful. 
If you have received this e-mail in error, please notify the sender by 
return e-mail and delete it from your computer immediately.*

**Comment by 14skywalker** [comment]
Can this be solved?

**Comment by djcesar** [comment]
+1

**Comment by josselex** [comment]
I will look into this the next days.

**Comment by bytecodeman** [comment]
This was submitted years ago. 

Delete this. 

Sent from my iPhone

> On Apr 24, 2017, at 11:32 AM, josselex <notifications@github.com> wrote:
> 
> I will look into this the next days.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
*SPRINGFIELD TECHNICAL COMMUNITY COLLEGE*
*IMPORTANT:  The information contained in this e-mail is intended solely 
for the person or entity to which it is addressed and may contain 
confidential and/or legally privileged material. Any use, disclosure, or 
taking of any action in reliance upon this information by any person and/or 
entity other than the intended recipient is prohibited and may be unlawful. 
If you have received this e-mail in error, please notify the sender by 
return e-mail and delete it from your computer immediately.*

**Comment by LiamKarlMitchell** [comment]
```
(index):955 Mixed Content: The page at 'https://site.co.nz/#test-bu' was loaded over HTTPS, but requested an insecure script 'http://browser-update.org/update.min.js'. This request has been blocked; the content must be served over HTTPS.
```
Still a problem today, copied script example from site trying to use it on a HTTPS URL.

```
<script> 
var $buoop = {required:{e:-4,f:-3,o:-3,s:-1,c:-3},insecure:true,unsupported:true,api:2018.07 }; 
function $buo_f(){ 
 var e = document.createElement("script"); 
 e.src = "//browser-update.org/update.min.js"; 
 document.body.appendChild(e);
};
try {document.addEventListener("DOMContentLoaded", $buo_f,false)}
catch(e){window.attachEvent("onload", $buo_f)}
</script>
```

**Comment by josselex** [comment]
I think the problem is with your site. When I try to visit it with Firefox,
it does not even open. It complains that the site is insecure. You have an
invalid certificate.
The certificat is only valid for
cdn0.undeveloped.com, cdn1.undeveloped.com, cdn2.undeveloped.com,
cdn3.undeveloped.com, undeveloped.com, web.undeveloped.com,
www.undeveloped.com
Errorcode: SSL_ERROR_BAD_CERT_DOMAIN

Am Do., 26. Juli 2018 um 07:54 Uhr schrieb Liam Mitchell <
notifications@github.com>:

**Comment by LiamKarlMitchell** [comment]
Oh, sorry I should note I just put site.co.nz as an example as to not disclose the current dev site.
Don't want spiders crawling over it just yet.

**Comment by josselex** [comment]
Ok. sorry. So I can't help, because I can't debug it. Works on thousands of
sites via https...

Am Do., 26. Juli 2018 um 22:49 Uhr schrieb Liam Mitchell <
notifications@github.com>:
