### ISSUE TITLE
Can't get warning to show to IE11 users

### ISSUE THREAD

**Issue by 29thfloor** [browser-update/browser-update#375]
I'm testing with IE11 on Windows 8.1

I've tried setting the IE value to 11, -4 and -3 and am still not seeing the warning. Seems to work fine for other outdated browsers.

**Comment by josselex** [comment]
Can you tell me what you see here?

http://browser-update.org/test.html

2018-01-15 2:43 GMT+01:00 Daniel McFarland <notifications@github.com>:

**Comment by 29thfloor** [comment]
I don't see the warning there. The content of the page looks like this:


Identification

User-Agent-String (HTTP Header):
Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko

User-Agent-String (Javascript): 
Mozilla/5.0 (Windows NT 6.3; Trident/7.0; .NET4.0E; .NET4.0C; rv:11.0) like Gecko

Detection

Detected Browser as (Javascript):
Internet Explorer 11
Warning: Your browser is misconfigured. Identification via Javascript and and HTTP-Headers does not match!

Browser (Header): 
Internet Explorer 11.0(i)

System (Header): 
Windows 8.1

Language


Lang (HTTP Header): 
en-US

Lang (Javascript): 
Error

**Comment by dashed** [comment]
I'm experiencing this issue for Win 7 for IE11.

**Comment by frankmichel** [comment]
Same here. Win 7 + IE11.

**Comment by RogerRehnelt** [comment]
Same here. Win10 + IE11. no warning :(

**Comment by Vardkin** [comment]
@josselex Thanks for the awesone lib. However, the issue with IE 11 + Win 7 still exists

**Comment by josselex** [comment]
Now it finally should work. Sorry for the delay. I was occupied with rewriting the whole browser-update.org site.

**Comment by jjnypr** [comment]
Not working w/ this config, no warning for IE11 on Windows 7:
```<script>
  (function() {
    window['$buoop'] = {required:{e:-5,f:-3,o:-3,s:-1,c:-3},shift_page_down:true,insecure:true,api:2019.03 };
    var e = document.createElement('script');
    e.src = '//browser-update.org/update.min.js';
    document.body.appendChild(e);
  })();
</script>
```

Here is what I'm getting from test.html:
```
User-Agent-String (HTTP Header):Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
User-Agent-String (Javascript): Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko
Detection
```

**Comment by philipdenys** [comment]
so it is still open?

couldn't get it to work on win7 IE11

**Comment by josselex** [comment]
Can you open your site with #test-bu appended to the url? Then you should always see the message with some debug information.

**Comment by josselex** [comment]
@philipdenys 
No, this bug is solved.
Can you open your site with #test-bu appended to the url? Then you should always see the message with some debug information.

**Comment by dennisgeerts** [comment]
I'm still having this issue with IE 11 on Windows 10. Goig to the test.html site returns me:

> Identification
> 
> User-Agent-String (HTTP Header):
> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
> 
> User-Agent-String (Javascript): 
> Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; rv:11.0) like Gecko
> 
> Detection
> 
> Detected Browser as (Javascript):
> Internet Explorer 11
> Warning: Your browser is misconfigured. Identification via Javascript and and HTTP-Headers does not match!
> 
> Browser (Header): 
> Internet Explorer 11
> 
> System (Header): 
> Windows 10
> 
> Language
> 
> Lang (HTTP Header): 
> nl-BE
> 
> Lang (Javascript): 
> nl

With #test-bu added to url in the debugging window it shows:

> Browser Notification Debug-Mode (v3.3.26)
> Browser would normally be notified: false
> **Browser info**
> is_latest:false, is_insecure:false, other:false, no_device_update:false, cookie set: true


I've tried clearing my cookies in IE.
